# Define the Dialyzer setup
default:
  image: elixir:latest
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - curl -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
    - rustup default stable

stages:
  - build
  - test

dialyzer:
  stage: build
  image: elixir:latest

  script:
    - mix dialyzer --plt

# Define the stages for the CI


# Define the job to build the project and set up Dialyzer
build:
  stage: build

  script:
    - mix compile
    - mix deps.compile

# Define the job to run tests
test:
  stage: test

  script:
    - mix compile --warnings-as-errors
    - mix credo --strict
    - mix dialyzer

variables:
  MIX_ENV: test
