# Define the Dialyzer setup
dialyzer_setup:
  stage: build
  image: elixir:latest

  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get

  script:
    - mix dialyzer --plt

# Define the stages for the CI
stages:
  - build
  - test

# Define the job to build the project and set up Dialyzer
build:
  stage: build
  image: elixir:latest

  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get

  script:
    - mix compile
    - mix deps.compile

  artifacts:
    paths:
      - _build
      - deps
      - priv/plts

# Define the job to run tests
test:
  stage: test
  image: elixir:latest

  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
  script:
    - mix compile --warnings-as-errors
    - mix credo --strict
    - mix dialyzer

variables:
  MIX_ENV: test
