default:
  image: elixir:latest
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - curl -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
    - rustup default stable

build:
  stage: build

  script:
    - mix compile
    - mix deps.compile

test:
  stage: test

  script:
    - mix compile --warnings-as-errors
    - mix credo

variables:
  MIX_ENV: test
